# サイトの基本設定
title: "Tsubaki Hosokawa | 細川 椿"
description: "Tsubaki Hosokawa's website"
url: "https://tsubakih07.github.io"
baseurl: "/tsubaki_homepage"
keywords: "Tsubaki Hosokawa | 細川 椿, Atmospheric Science, Orographic Precipitation, Tropical Cyclones, Polarimetric Radar"

# SEOと構造化データ
author:
  name: "Tsubaki Hosokawa | 細川 椿"
  bio: "Ph.D. candidate in Atmospheric Sciences, National Taiwan University"

# ソース/出力設定
markdown: kramdown

# # ページごとのデフォルト設定
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# # プラグイン
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude（ビルドから除外するファイル）
# GitHub Pages に適した設定
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json

google_analytics: G-SGBM1LF08E