info_en:
  name: Tsubaki Hosokawa
  email: tsubakih07❄gmail.com
  position: Postdoctoral Researcher
  affiliation: National Taiwan University
  department: Department of Atmospheric Sciences
  location: Taipei, Taiwan

info_ja:
  name: 細川 椿
  email: tsubakih07❄gmail.com
  position: ポスドク研究員
  affiliation: 国立台湾大学
  department: 大気科学系
  location: 台湾台北市

links:
  google_scholar: https://scholar.google.com/citations?user=PhdBZk0AAAAJ&hl=ja&oi=ao
  orcid: https://orcid.org/0009-0004-5857-045X
  github: https://github.com/tsubakih07